### ISSUE TITLE
Cannot set property 'proxy' of undefined

### ISSUE THREAD

**Issue by endertls** [vikki/nightmob#1]
Hello,
I try to run browsermob with nightwatch and your git seems to have all I need but I'm facing an error when I launch your basicTest.js.

After launching browsermob-proxy and selenium, if I launch nightwatch I have the following message and I don't figure why : 
An error occurred while running the tests:
TypeError: Cannot set property 'proxy' of undefined
    at /home/john/BrowserMob/testnightwatch/setUp/setupProxy.js:11:48
    at /home/john/BrowserMob/testnightwatch/node_modules/browsermob-proxy/index.js:87:17
    at IncomingMessage.<anonymous> (/home/john/BrowserMob/testnightwatch/node_modules/browsermob-proxy/index.js:229:21)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)% 

Do you know how to resolve this ?

Thank you

**Comment by Khanivorous** [comment]
Hi, I get the same error too

**Comment by AlexKovalevych** [comment]
In `setupProxy.js` try to change the line

``` javascript
nightwatchClient.desiredCapabilities.proxy = ...
```

to line

``` javascript
nightwatchClient.options.desiredCapabilities.proxy = ...
```
